# Generated by Django 5.2 on 2025-05-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_tracking_url_cart_cart_user_or_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество товаров в заказе'),
        ),
    ]
