# Generated by Django 5.2 on 2025-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз СДЭК'), ('courier', 'Курьером СДЭК')], default='pickup', max_length=20),
        ),
    ]
